


---

- name: add group "tomcat"
  group: name={{tomcat_group}}

- name: add user "tomcat"
  user: name={{tomcat_user}} group={{tomcat_group}} home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo

- name: Download Tomcat
  copy: src=apache-tomcat-8.5.42.tar.gz dest=/opt/apache-tomcat-8.5.42.tar.gz mode=0755

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-8.5.42.tar.gz -C /opt/ creates=/opt/apache-tomcat-8.5.42
- name: Symlink install directory
  file: src=/opt/apache-tomcat-8.5.42 path=/usr/share/tomcat state=link

- name: Change ownership of Tomcat installation
  file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: Configure Tomcat server
  template: src=server.xml dest=/usr/share/tomcat/conf/

  
- name: Create  sample directory
  file: 
    path: "/opt/apache-tomcat-8.5.42/webapps/samples"
    state: directory
    mode: 0777
  become: true
  

- name: copy war file
  copy: src=./target/LoginWebApp-1.war dest=/opt/apache-tomcat-8.5.42/webapps/


  notify: restart tomcat

- name: Install Tomcat systemd Script
  copy: src=tomcat-systemd.sh dest=/etc/systemd/system/tomcat.service mode=0755

- name: Start Tomcat
  service: name=tomcat state=started enabled=yes

- name: wait for tomcat to start
  wait_for: port={{http_port}}
     
